### ISSUE TITLE
test_combine_kp_inst_time locally fails

### ISSUE THREAD

**Issue by jklenzing** [rstoneback/pysat#195]
In test_sw.py, test_combine_kp_inst_time fails when run locally (note this test is skipped on Travis CI due to requiring downloads).
```
======================================================================
ERROR: Test combine_kp when times are provided through the instruments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jklenzing/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jklenzing/code/pysat/pysat/tests/test_sw.py", line 215, in test_combine_kp_inst_time
    fill_val = combo_in['standard_inst'].meta['Kp'][kp_inst.meta.fill_label]
  File "/Users/jklenzing/code/pysat/pysat/_meta.py", line 593, in __getitem__
    raise KeyError('Key not found in MetaData')
KeyError: 'Key not found in MetaData'
```

**Comment by jklenzing** [comment]
Line references above for pull #192.  In `develop`, this is Line 198.

**Comment by jklenzing** [comment]
Closing since root problem is documenting in #198.
