### ISSUE TITLE
negative year from c/nofs instrument

### ISSUE THREAD

**Issue by JonathonMSmith** [rstoneback/pysat#87]
From a fresh install and newly downloaded data in a conda virtual environment:
```
>>>ivm = pysat.Instrument(platform='cnofs', name='ivm')
>>>start = pysat.datetime(2013,12,30)
>>>stop = pysat.datetime(2014,1,30)
>>>ivm.bounds = (start, stop)
>>> ivm.load(date=stop)
```
This yields the output :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/_instrument.py", 
line 879, in load
    self.data, meta = self._load_data(date=self.date, fid=self._fid) 
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/_instrument.py", 
line 622, in _load_data
    sat_id=self.sat_id, **self.kwargs)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/instruments/nasa_cdaweb_methods.py", 
line 157, in load
    return cdf.to_pysat(flatten_twod=flatten_twod)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysatCDF/_cdf.py", 
line 658, in to_pysat
    columns=new_names)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py", 
line 379, in __init__
    copy=copy)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py", 
line 527, in _init_ndarray
    index, columns = _get_axes(*values.shape)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py", 
line 484, in _get_axes
    index = _ensure_index(index)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/base.py", 
line 4974, in _ensure_index
    return Index(index_like)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/base.py", 
line 294, in __new__
    dtype=dtype, **kwargs)
  File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", 
line 422, in __new__
    subarr = conversion.ensure_datetime64ns(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 119, in pandas._libs.tslibs.conversion.ensure_datetime64ns
  File "pandas/_libs/tslibs/np_datetime.pyx", line 121, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: -1-12-31 23:59:59
```
This appears to only happen on dates between 2014-01-04 and 2014-01-31
This doesn't happen for other dates

**Comment by rstoneback** [comment]
Thanks Jonathon,

The error originates in pysatCDF as it is putting data from the CDF file into a data frame. The date it puts out, 1-12-31 is pretty weird.

Going back a version or two on pandas may get you going temporarily.

I will put this on the list.

Russell

On Oct 5, 2018, at 11:45 AM, Jonathon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


From a fresh install and newly downloaded data in a conda virtual environment:

>>>ivm = pysat.Instrument(platform='cnofs', name='ivm')
>>>start = pysat.datetime(2013,12,30)
>>>stop = pysat.datetime(2014,1,30)
>>>ivm.bounds = (start, stop)
>>> ivm.load(date=stop)


This yields the output :
Traceback (most recent call last):
File "", line 1, in
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/_instrument.py",
line 879, in load
self.data, meta = self._load_data(date=self.date, fid=self._fid)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/_instrument.py",
line 622, in _load_data
sat_id=self.sat_id, **self.kwargs)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysat/instruments/nasa_cdaweb_methods.py",
line 157, in load
return cdf.to_pysat(flatten_twod=flatten_twod)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pysatCDF/_cdf.py",
line 658, in to_pysat
columns=new_names)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py",
line 379, in init
copy=copy)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py",
line 527, in _init_ndarray
index, columns = _get_axes(*values.shape)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/frame.py",
line 484, in _get_axes
index = _ensure_index(index)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/base.py",
line 4974, in _ensure_index
return Index(index_like)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/base.py",
line 294, in new
dtype=dtype, **kwargs)
File "~~~/anaconda3/envs/pysat_test/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py",
line 422, in new
subarr = conversion.ensure_datetime64ns(data)
File "pandas/_libs/tslibs/conversion.pyx", line 119, in pandas._libs.tslibs.conversion.ensure_datetime64ns
File "pandas/_libs/tslibs/np_datetime.pyx", line 121, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: -1-12-31 23:59:59

This appears to only happen on dates between 2014-01-04 and 2014-01-31
This doesn't happen for other dates

**Comment by jklenzing** [comment]
I double-checked on the CDAweb archive, and the online data viewer at https://cdaweb.sci.gsfc.nasa.gov/cgi-bin/eval3.cgi also fails to grab data for these days.  This may be a problem with the dataset itself.

**Comment by jklenzing** [comment]
I will check with CDAweb to see if they have the data files.

**Comment by jklenzing** [comment]
The files exist on the server.  Manually downloaded and opened with pysatCDF, and found that these dates give negative epochs after the first value.

In [33]: cdf.data['Epoch']                                                            
Out[33]: 
array(['2014-01-04T00:00:03.737', '-001-12-31T23:59:59.999',
       '0006-01-13T01:36:13.833', ..., '-001-12-31T23:59:59.999',
       '-001-12-31T23:59:59.999', '0000-01-01T00:00:00.000'],
      dtype='datetime64[ms]')

Nothing new.  The hdf files are up on the server as well, but I can't read these.  Could @rstoneback check if the files sent to SPDF have proper epochs?

**Comment by rstoneback** [comment]
Pinging myself so I don't forget. @rstoneback

**Comment by aburrell** [comment]
It looks like what we need to do is put in an error catch for a bad timestamp occurring when loading any data:

```
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: -1-12-31 23:59:59
```

We should not return any data for this file, but not completely die when doing something like a seasonal average where we can just happily keep going for other days.  That way pysat will still work without the user or data server having to maintain a totally clean file list (since this is not realistic).

**Comment by rstoneback** [comment]
I've pinged local CINDI personnel about the time in the file

**Comment by jklenzing** [comment]
Merged fixes for load routine to develop.
